MyProfile Page Displays User Details & Image -- minimal changes to server-side (see below)
NSS-Day-Cohort-42/rare-server-fakes-news pull request #7
Opened 2020-10-23 21:01 UTC by justha

​
## Description
Need to merge with main to make sure it captures latest version, due to possible merge issues earlier. 

​
## How do I access this branch?
`git checkout main`
`git fetch --all`
`git checkout hn-MyProfile`
`watchgod request_handler.main`

​
## Motivation and Context

​
## How Has This Been Tested?

​
## Screenshots (if appropriate):
​
## Types of changes
There should be minimal or no changes to server-side code, but need to merge with Main branch to confirm. 

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
​
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-10-23 22:05 UTC, egeehartz requested changes
I think I need more clarification about the changes that were made.
I get a key error when I try to register a user. All of the user methods have different keys, so I wanted to double check with you how you dropped the user table and added it back in. 

I'll make this comment on the frontend as well, but creating the user object in Register.js doesn't match the backend (missing first name, last name)

2020-10-26 15:38 UTC, egeehartz approved these changes

2020-10-26 15:39 UTC, esthersanders approved these changes

2020-10-26 15:39 UTC, merged

2020-10-26 15:48 UTC, justha commented
Added user first and last name to registration form and all user table requests. Ok now.